name: Generate AAB File Free Playstore

on: 
  workflow_dispatch:
    inputs:
        ref:
          description: 'Reference branch, tag, commit id'
          required: true
          type: string
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleFreePlaystoreRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@fix/bundle-signing
        with:
          releaseDirectory: app/build/outputs/bundle/freePlaystoreRelease
          signingKeyBase64: ${{ secrets.PLAY_STORE_UPLOAD_SIGNING_KEY }}
          alias: ${{ secrets.PLAY_STORE_UPLOAD_ALIAS  }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: 🚀 Upload APK to Artifacts 📱
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/bundle/freePlaystoreRelease/*.aab
          retention-days: 3
