name: Submit to Play Store (Pro)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Github release version'
        required: true
        type: string
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Echo Release name
        run: |
          echo "${{ github.ref_name || github.event.inputs.version }}"

      - name: Build Release AAB
        run: ./gradlew bundleProRelease

      - name: Sign Release AAB
        id: signAAB
        uses: r0adkll/sign-android-release@fix/bundle-signing
        with:
          releaseDirectory: app/build/outputs/bundle/pro/release
          signingKeyBase64: ${{ secrets.PLAY_STORE_UPLOAD_SIGNING_KEY }}
          alias: ${{ secrets.PLAY_STORE_UPLOAD_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy Free to Play Store (PROD) (Free)
        id: deployFreeProd
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.yogeshpaliyal.deepr
          releaseFiles: app/build/outputs/bundle/pro/release/*.aab
          track: alpha
          whatsNewDirectory: whatsnew/

