name: PR Check

on:
  pull_request:
    branches: [ master, yogesh ]
    paths-ignore:
      - 'fastlane/**'
      - '.github/**'
      - 'icons/**'
      - 'images/**'
      - 'scripts/**'
      - 'whatsnew/**'
      - '**.md'
      - '**.MD'

# If two events are triggered within a short time in the same PR, cancel the run of the oldest event
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate-pr:
    name: 'Tests and Build Production Debug Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Lint Check
        run: bash ./gradlew lintKotlin

      - name: 🏗 Disable Firebase
        run: |
          bash ./scripts/enableDisableFirebase.sh false

      - name: 🏗 Build Github APK
        run: bash ./gradlew assembleGithubDebug

      - name: 🏗 Enable Firebase
        run: |
          bash ./scripts/enableDisableFirebase.sh true

      - name: 🏗 Build Free Play store APK
        run: bash ./gradlew assembleFreeDebug

      - name: 🏗 Build Pro APK
        run: bash ./gradlew assembleProDebug

      - name: 🚀 Upload APK to Artifacts 📱
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/github/debug/*.apk
          retention-days: 3


